### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by NikolaiT** [adrienv1520/node-uri#7]
I am dev looking out for a URL validator. 

The reason why I will never use a module such as this one:

It is waaaaaaaaaaaaaay to complex. There is no straightforward example, and all the complexity is thrown in my face on the README page.

I get that URL validation is a hard problem. I really do. 

But give me an easy module and state in a short phrase the pitfalls and I might use it.

**Comment by ob-aion** [comment]
Hi,

I don't find your comment useful or kind at all.

I don't agree with you I think the documentation is good for an open-source project and every method is explained with examples. If you can't read a documentation I'm sorry I can't do anything for you.

If you want an easy module to use that won't follow the standars and raise many errors, there's plenty out there. It's totally up to you.

And if you want to contribute and improve it, simplify it, you still can do it.
