### ISSUE TITLE
Does not work - get index.js:1 TypeError: domainToASCII is not a function

### ISSUE THREAD

**Issue by zehawki** [adrienv1520/node-uri#8]
Error as follows when trying to use checkURI or checkWebURL with any URL:

```
index.js:1 TypeError: domainToASCII is not a function
    at punycode (index.js:31)
    at parseURI (index.js:224)
    at checkURISyntax (index.js:284)
    at checkURI (index.js:393)
    at checkHttpURL (index.js:479)
    at checkWebURL (index.js:615)
```

**Comment by ob-aion** [comment]
Hey,

Sorry for the late reply.

I suspect you are using an old version of Node.js which is why you have this error: [url.domainToASCII was added in: v7.4.0, v6.13.0](https://nodejs.org/api/url.html#urldomaintoasciidomain).

As mentioned in the docs you should at least have Node.js v8.17.0.

**Comment by ob-aion** [comment]
I'm closing this issue but if you have any other issue please feel free to open a new one again :)

**Comment by ob-aion** [comment]
Tested with Node.js < 6 and I have the same issue.

Please update youre Node.js version and you should be good.

Thanks 🙏
